### ISSUE TITLE
Mod does not create a config?

### ISSUE THREAD

**Issue by MusuNezumi** [IOL-Haven/discord-verifier#1]
tried adding this mod to a server to see if it works, the mod did not create a config file, and will crash the server on start.

**Comment by TechnoPorg** [comment]
Thanks for reporting the bug! I will push a fix within the next couple of days :crossed_fingers:

**Comment by shlyapniq** [comment]
same, config is not created and server is crashed

**Comment by TechnoPorg** [comment]
@MusuNezumi @shlyapniq I've fixed the crash and the config issue on the main branch.
If you could please test it on your servers using the JARs [from the latest build artifacts](https://github.com/IOL-Haven/discord-verifier/actions/runs/10864231100/artifacts/1933422589) before I push a release for version 1.0.2, that would be much appreciated.

**Comment by MusuNezumi** [comment]
Appears to not crash and the config is made, when trying to verify with the / command the application would not respond(the bot is in fact online)

**Comment by TechnoPorg** [comment]
Interesting. I can't replicate that issue on my end, so I suspect it is something to do with the way you have the Discord application configured.
I'm going to close this issue and push a new release to fix the original bug, but please open a new issue about the unresponsiveness (with relevant logs) when you have time!
